### ISSUE TITLE
Language Selections

### ISSUE THREAD

**Issue by Tyrim** [ZWinther/lotr5e-module#21]
When selection a language, it automatically selects a bunch of other languages, and I cannot remove them. Choosing any language results in the following languages being selected automatically, and nothing I do will remove them from the sheet once this happens: Black Speech, Dalish, Orkish, and Sindarin.

**Comment by ZWinther** [comment]
Hey there, I can't reproduce that error on my end.

Is it on directly from the character sheet or through an advancement?

**Comment by Tyrim** [comment]
Through the character sheet. It happens with both NPCs and PCs sheets.

**Comment by ZWinther** [comment]
Alright, since I can't recreate the problem you'll have to collect some info for me to track down what the issue is.

First off, open the developer console with F12 before loading into the world, try selecting some languages and then check the console for any errors.

Other than that, please list what versions of the following, that you have installed:

- This module
- The libWrapper module
- The dnd5e system
- FoundryVTT itself

Finally, if you're using any other modules, try creating a new dnd5e world with only LotR5e and libWrapper enabled, to check if there could be some compatibility issue.
